# Data-related settings
data_dir: 'data/'
n_vars: 6
n_steps: 128

# Training settings
device: cuda
seed: 0
batch_size: 256
n_epochs: 200

# Algorithm-related settings
algo: GAN
generator: TCN
discriminator: TCN

# Model settings
G_input_dim: 3 # Noise dimension
D_input_dim: 1 # Noise dimension
hidden_dim: 80
output_dim: 1
noise_dim: 3

# Learning rates
lr_G: 0.0002
lr_D: 0.0001
D_steps_per_G_step: 1
corr_loss_type: 'l1'       # 'l2' or 'l1' or 'fro'
corr_weight: 5
lambda_gp: 10.0

# Additional settings
gp: True
W: 10.0                   # scale parameter for W
alphas: [0.05]            # quantiles
score: 'quant'            # score function
project: True             # Project into constraint set
temp: 1 # 0.01            # multiplier of temperature
latent_dim: 256 # 1000    # dimensionality of the latent space

